package candy_raylib

import (
	"candy/candy_evaluator"
)

func RegisterBuiltins() {
	// rcore
	candy_evaluator.RegisterBuiltin("initWindow", builtinInitWindow)
	candy_evaluator.RegisterBuiltin("window", builtinInitWindow)
	candy_evaluator.RegisterBuiltin("closeWindow", builtinCloseWindow)
	candy_evaluator.RegisterBuiltin("windowShouldClose", builtinWindowShouldClose)
	candy_evaluator.RegisterBuiltin("shouldClose", builtinWindowShouldClose)
	candy_evaluator.RegisterBuiltin("setTargetFPS", builtinSetTargetFPS)
	candy_evaluator.RegisterBuiltin("beginDrawing", builtinBeginDrawing)
	candy_evaluator.RegisterBuiltin("endDrawing", builtinEndDrawing)
	candy_evaluator.RegisterBuiltin("show", builtinEndDrawing)
	candy_evaluator.RegisterBuiltin("clearBackground", builtinClearBackground)
	candy_evaluator.RegisterBuiltin("clear", builtinClearBackground)
	candy_evaluator.RegisterBuiltin("getScreenWidth", builtinGetScreenWidth)
	candy_evaluator.RegisterBuiltin("getScreenHeight", builtinGetScreenHeight)
	candy_evaluator.RegisterBuiltin("getFrameTime", builtinGetFrameTime)
	candy_evaluator.RegisterBuiltin("getTime", builtinGetTime)
	candy_evaluator.RegisterBuiltin("getFPS", builtinGetFPS)
	candy_evaluator.RegisterBuiltin("isWindowReady", builtinIsWindowReady)
	candy_evaluator.RegisterBuiltin("setExitKey", builtinSetExitKey)
	candy_evaluator.RegisterBuiltin("flip", builtinFlip)
	candy_evaluator.RegisterBuiltin("takeScreenshot", builtinTakeScreenshot)
	candy_evaluator.RegisterBuiltin("setWindowTitle", builtinSetWindowTitle)
	candy_evaluator.RegisterBuiltin("setWindowSize", builtinSetWindowSize)
	candy_evaluator.RegisterBuiltin("maximizeWindow", builtinMaximizeWindow)
	candy_evaluator.RegisterBuiltin("minimizeWindow", builtinMinimizeWindow)
	candy_evaluator.RegisterBuiltin("restoreWindow", builtinRestoreWindow)
	candy_evaluator.RegisterBuiltin("isWindowFullscreen", builtinIsWindowFullscreen)
	candy_evaluator.RegisterBuiltin("toggleFullscreen", builtinToggleFullscreen)
	// window state checks
	candy_evaluator.RegisterBuiltin("isWindowHidden", builtinIsWindowHidden)
	candy_evaluator.RegisterBuiltin("isWindowMinimized", builtinIsWindowMinimized)
	candy_evaluator.RegisterBuiltin("isWindowMaximized", builtinIsWindowMaximized)
	candy_evaluator.RegisterBuiltin("isWindowFocused", builtinIsWindowFocused)
	candy_evaluator.RegisterBuiltin("isWindowResized", builtinIsWindowResized)
	candy_evaluator.RegisterBuiltin("isWindowState", builtinIsWindowState)
	// window state mutators
	candy_evaluator.RegisterBuiltin("setWindowState", builtinSetWindowState)
	candy_evaluator.RegisterBuiltin("clearWindowState", builtinClearWindowState)
	candy_evaluator.RegisterBuiltin("toggleBorderlessWindowed", builtinToggleBorderlessWindowed)
	candy_evaluator.RegisterBuiltin("setWindowPosition", builtinSetWindowPosition)
	candy_evaluator.RegisterBuiltin("setWindowMonitor", builtinSetWindowMonitor)
	candy_evaluator.RegisterBuiltin("setWindowMinSize", builtinSetWindowMinSize)
	candy_evaluator.RegisterBuiltin("setWindowMaxSize", builtinSetWindowMaxSize)
	candy_evaluator.RegisterBuiltin("setWindowOpacity", builtinSetWindowOpacity)
	candy_evaluator.RegisterBuiltin("setWindowFocused", builtinSetWindowFocused)
	// window icon
	candy_evaluator.RegisterBuiltin("setWindowIcon", builtinSetWindowIcon)
	candy_evaluator.RegisterBuiltin("setWindowIcons", builtinSetWindowIcons)
	// render size
	candy_evaluator.RegisterBuiltin("getRenderWidth", builtinGetRenderWidth)
	candy_evaluator.RegisterBuiltin("getRenderHeight", builtinGetRenderHeight)
	// monitor queries
	candy_evaluator.RegisterBuiltin("getMonitorCount", builtinGetMonitorCount)
	candy_evaluator.RegisterBuiltin("getCurrentMonitor", builtinGetCurrentMonitor)
	candy_evaluator.RegisterBuiltin("getMonitorPosition", builtinGetMonitorPosition)
	candy_evaluator.RegisterBuiltin("getMonitorWidth", builtinGetMonitorWidth)
	candy_evaluator.RegisterBuiltin("getMonitorHeight", builtinGetMonitorHeight)
	candy_evaluator.RegisterBuiltin("getMonitorPhysicalWidth", builtinGetMonitorPhysicalWidth)
	candy_evaluator.RegisterBuiltin("getMonitorPhysicalHeight", builtinGetMonitorPhysicalHeight)
	candy_evaluator.RegisterBuiltin("getMonitorRefreshRate", builtinGetMonitorRefreshRate)
	candy_evaluator.RegisterBuiltin("getMonitorName", builtinGetMonitorName)
	// window position / DPI / handle
	candy_evaluator.RegisterBuiltin("getWindowPosition", builtinGetWindowPosition)
	candy_evaluator.RegisterBuiltin("getWindowScaleDPI", builtinGetWindowScaleDPI)
	candy_evaluator.RegisterBuiltin("getWindowHandle", builtinGetWindowHandle)
	// clipboard image + event waiting
	candy_evaluator.RegisterBuiltin("getClipboardImage", builtinGetClipboardImage)
	candy_evaluator.RegisterBuiltin("enableEventWaiting", builtinEnableEventWaiting)
	candy_evaluator.RegisterBuiltin("disableEventWaiting", builtinDisableEventWaiting)
	// cursor
	candy_evaluator.RegisterBuiltin("showCursor", builtinShowCursor)
	candy_evaluator.RegisterBuiltin("hideCursor", builtinHideCursor)
	candy_evaluator.RegisterBuiltin("isCursorHidden", builtinIsCursorHidden)
	candy_evaluator.RegisterBuiltin("enableCursor", builtinEnableCursor)
	candy_evaluator.RegisterBuiltin("disableCursor", builtinDisableCursor)
	candy_evaluator.RegisterBuiltin("isCursorOnScreen", builtinIsCursorOnScreen)

	// input
	candy_evaluator.RegisterBuiltin("isKeyPressed", builtinIsKeyPressed)
	candy_evaluator.RegisterBuiltin("isKeyDown", builtinIsKeyDown)
	candy_evaluator.RegisterBuiltin("key", builtinIsKeyDown)
	candy_evaluator.RegisterBuiltin("isKeyReleased", builtinIsKeyReleased)
	candy_evaluator.RegisterBuiltin("isKeyUp", builtinIsKeyUp)
	candy_evaluator.RegisterBuiltin("getMouseX", builtinGetMouseX)
	candy_evaluator.RegisterBuiltin("getMouseY", builtinGetMouseY)
	candy_evaluator.RegisterBuiltin("getMousePosition", builtinGetMousePosition)
	candy_evaluator.RegisterBuiltin("isMouseButtonPressed", builtinIsMouseButtonPressed)
	candy_evaluator.RegisterBuiltin("isMouseButtonDown", builtinIsMouseButtonDown)
	candy_evaluator.RegisterBuiltin("isMouseButtonReleased", builtinIsMouseButtonReleased)
	candy_evaluator.RegisterBuiltin("getMouseWheelMove", builtinGetMouseWheelMove)
	candy_evaluator.RegisterBuiltin("setClipboardText", builtinSetClipboardText)
	candy_evaluator.RegisterBuiltin("getClipboardText", builtinGetClipboardText)
	candy_evaluator.RegisterBuiltin("isGamepadAvailable", builtinIsGamepadAvailable)
	candy_evaluator.RegisterBuiltin("isGamepadButtonPressed", builtinIsGamepadButtonPressed)
	candy_evaluator.RegisterBuiltin("isGamepadButtonDown", builtinIsGamepadButtonDown)
	candy_evaluator.RegisterBuiltin("getGamepadName", builtinGetGamepadName)
	candy_evaluator.RegisterBuiltin("getGamepadAxisValue", builtinGetGamepadAxisValue)

	// rcore — drawing extras
	candy_evaluator.RegisterBuiltin("beginScissorMode", builtinBeginScissorMode)
	candy_evaluator.RegisterBuiltin("endScissorMode", builtinEndScissorMode)
	candy_evaluator.RegisterBuiltin("beginBlendMode", builtinBeginBlendMode)
	candy_evaluator.RegisterBuiltin("endBlendMode", builtinEndBlendMode)
	// rcore — screen-space
	candy_evaluator.RegisterBuiltin("getScreenToWorldRay", builtinGetScreenToWorldRay)
	candy_evaluator.RegisterBuiltin("getScreenToWorldRayEx", builtinGetScreenToWorldRayEx)
	candy_evaluator.RegisterBuiltin("getWorldToScreen", builtinGetWorldToScreen)
	candy_evaluator.RegisterBuiltin("getWorldToScreenEx", builtinGetWorldToScreenEx)
	candy_evaluator.RegisterBuiltin("getWorldToScreen2D", builtinGetWorldToScreen2D)
	candy_evaluator.RegisterBuiltin("getScreenToWorld2D", builtinGetScreenToWorld2D)
	candy_evaluator.RegisterBuiltin("getCameraMatrix", builtinGetCameraMatrix)
	candy_evaluator.RegisterBuiltin("getCameraMatrix2D", builtinGetCameraMatrix2D)
	// rcore — frame control
	candy_evaluator.RegisterBuiltin("swapScreenBuffer", builtinSwapScreenBuffer)
	candy_evaluator.RegisterBuiltin("pollInputEvents", builtinPollInputEvents)
	candy_evaluator.RegisterBuiltin("waitTime", builtinWaitTime)
	// rcore — random
	candy_evaluator.RegisterBuiltin("setRandomSeed", builtinSetRandomSeed)
	candy_evaluator.RegisterBuiltin("getRandomValue", builtinGetRandomValue)
	// rcore — misc
	candy_evaluator.RegisterBuiltin("setConfigFlags", builtinSetConfigFlags)
	candy_evaluator.RegisterBuiltin("openURL", builtinOpenURL)
	candy_evaluator.RegisterBuiltin("setTraceLogLevel", builtinSetTraceLogLevel)
	// rcore — shader extras
	candy_evaluator.RegisterBuiltin("loadShaderFromMemory", builtinLoadShaderFromMemory)
	candy_evaluator.RegisterBuiltin("isShaderValid", builtinIsShaderValid)
	candy_evaluator.RegisterBuiltin("getShaderLocation", builtinGetShaderLocation)
	candy_evaluator.RegisterBuiltin("getShaderLocationAttrib", builtinGetShaderLocationAttrib)
	candy_evaluator.RegisterBuiltin("setShaderValue", builtinSetShaderValue)
	candy_evaluator.RegisterBuiltin("setShaderValueMatrix", builtinSetShaderValueMatrix)
	candy_evaluator.RegisterBuiltin("setShaderValueTexture", builtinSetShaderValueTexture)
	// rcore — keyboard extras
	candy_evaluator.RegisterBuiltin("isKeyPressedRepeat", builtinIsKeyPressedRepeat)
	candy_evaluator.RegisterBuiltin("getKeyPressed", builtinGetKeyPressed)
	candy_evaluator.RegisterBuiltin("getCharPressed", builtinGetCharPressed)
	// rcore — mouse extras
	candy_evaluator.RegisterBuiltin("isMouseButtonUp", builtinIsMouseButtonUp)
	candy_evaluator.RegisterBuiltin("getMouseDelta", builtinGetMouseDelta)
	candy_evaluator.RegisterBuiltin("setMousePosition", builtinSetMousePosition)
	candy_evaluator.RegisterBuiltin("setMouseOffset", builtinSetMouseOffset)
	candy_evaluator.RegisterBuiltin("setMouseScale", builtinSetMouseScale)
	candy_evaluator.RegisterBuiltin("getMouseWheelMoveV", builtinGetMouseWheelMoveV)
	candy_evaluator.RegisterBuiltin("setMouseCursor", builtinSetMouseCursor)
	// rcore — gamepad extras
	candy_evaluator.RegisterBuiltin("isGamepadButtonReleased", builtinIsGamepadButtonReleased)
	candy_evaluator.RegisterBuiltin("isGamepadButtonUp", builtinIsGamepadButtonUp)
	candy_evaluator.RegisterBuiltin("getGamepadButtonPressed", builtinGetGamepadButtonPressed)
	candy_evaluator.RegisterBuiltin("getGamepadAxisCount", builtinGetGamepadAxisCount)
	candy_evaluator.RegisterBuiltin("setGamepadMappings", builtinSetGamepadMappings)
	candy_evaluator.RegisterBuiltin("setGamepadVibration", builtinSetGamepadVibration)
	// rcore — touch
	candy_evaluator.RegisterBuiltin("getTouchX", builtinGetTouchX)
	candy_evaluator.RegisterBuiltin("getTouchY", builtinGetTouchY)
	candy_evaluator.RegisterBuiltin("getTouchPosition", builtinGetTouchPosition)
	candy_evaluator.RegisterBuiltin("getTouchPointId", builtinGetTouchPointId)
	candy_evaluator.RegisterBuiltin("getTouchPointCount", builtinGetTouchPointCount)
	// rgestures
	candy_evaluator.RegisterBuiltin("setGesturesEnabled", builtinSetGesturesEnabled)
	candy_evaluator.RegisterBuiltin("isGestureDetected", builtinIsGestureDetected)
	candy_evaluator.RegisterBuiltin("getGestureDetected", builtinGetGestureDetected)
	candy_evaluator.RegisterBuiltin("getGestureHoldDuration", builtinGetGestureHoldDuration)
	candy_evaluator.RegisterBuiltin("getGestureDragVector", builtinGetGestureDragVector)
	candy_evaluator.RegisterBuiltin("getGestureDragAngle", builtinGetGestureDragAngle)
	candy_evaluator.RegisterBuiltin("getGesturePinchVector", builtinGetGesturePinchVector)
	candy_evaluator.RegisterBuiltin("getGesturePinchAngle", builtinGetGesturePinchAngle)
	// rcamera
	candy_evaluator.RegisterBuiltin("updateCamera", builtinUpdateCamera)
	candy_evaluator.RegisterBuiltin("updateCameraPro", builtinUpdateCameraPro)
	// file drop
	candy_evaluator.RegisterBuiltin("isFileDropped", builtinIsFileDropped)
	candy_evaluator.RegisterBuiltin("loadDroppedFiles", builtinLoadDroppedFiles)

	// rshapes
	candy_evaluator.RegisterBuiltin("drawPixel", builtinDrawPixel)
	candy_evaluator.RegisterBuiltin("drawLine", builtinDrawLine)
	candy_evaluator.RegisterBuiltin("line", builtinDrawLine)
	candy_evaluator.RegisterBuiltin("drawCircle", builtinDrawCircle)
	candy_evaluator.RegisterBuiltin("circle", builtinDrawCircle)
	candy_evaluator.RegisterBuiltin("drawCircleLines", builtinDrawCircleLines)
	candy_evaluator.RegisterBuiltin("drawEllipse", builtinDrawEllipse)
	candy_evaluator.RegisterBuiltin("drawRing", builtinDrawRing)
	candy_evaluator.RegisterBuiltin("drawRectangle", builtinDrawRectangle)
	candy_evaluator.RegisterBuiltin("box", builtinDrawRectangle)
	candy_evaluator.RegisterBuiltin("rectangle", builtinDrawRectangle)
	candy_evaluator.RegisterBuiltin("drawRectangleLines", builtinDrawRectangleLines)
	candy_evaluator.RegisterBuiltin("drawRectangleRounded", builtinDrawRectangleRounded)
	candy_evaluator.RegisterBuiltin("drawTriangle", builtinDrawTriangle)
	candy_evaluator.RegisterBuiltin("drawFPS", builtinDrawFPS)
	candy_evaluator.RegisterBuiltin("fps", builtinSetTargetFPS)
	candy_evaluator.RegisterBuiltin("exit", builtinCloseWindow)
	candy_evaluator.RegisterBuiltin("wait", builtinWaitTime)
	candy_evaluator.RegisterBuiltin("mouseX", builtinGetMouseX)
	candy_evaluator.RegisterBuiltin("mouseY", builtinGetMouseY)
	candy_evaluator.RegisterBuiltin("clicked", builtinClicked)
	candy_evaluator.RegisterBuiltin("checkCollisionRecs", builtinCheckCollisionRecs)
	candy_evaluator.RegisterBuiltin("checkCollisionCircles", builtinCheckCollisionCircles)
	candy_evaluator.RegisterBuiltin("checkCollisionCircleRec", builtinCheckCollisionCircleRec)
	// rshapes — shapes texture
	candy_evaluator.RegisterBuiltin("setShapesTexture", builtinSetShapesTexture)
	candy_evaluator.RegisterBuiltin("getShapesTexture", builtinGetShapesTexture)
	candy_evaluator.RegisterBuiltin("getShapesTextureRectangle", builtinGetShapesTextureRectangle)
	// rshapes — pixel/line V/Ex
	candy_evaluator.RegisterBuiltin("drawPixelV", builtinDrawPixelV)
	candy_evaluator.RegisterBuiltin("drawLineV", builtinDrawLineV)
	candy_evaluator.RegisterBuiltin("drawLineEx", builtinDrawLineEx)
	candy_evaluator.RegisterBuiltin("drawLineStrip", builtinDrawLineStrip)
	candy_evaluator.RegisterBuiltin("drawLineBezier", builtinDrawLineBezier)
	candy_evaluator.RegisterBuiltin("drawLineDashed", builtinDrawLineDashed)
	// rshapes — circle variants
	candy_evaluator.RegisterBuiltin("drawCircleV", builtinDrawCircleV)
	candy_evaluator.RegisterBuiltin("drawCircleGradient", builtinDrawCircleGradient)
	candy_evaluator.RegisterBuiltin("drawCircleSector", builtinDrawCircleSector)
	candy_evaluator.RegisterBuiltin("drawCircleSectorLines", builtinDrawCircleSectorLines)
	candy_evaluator.RegisterBuiltin("drawCircleLinesV", builtinDrawCircleLinesV)
	candy_evaluator.RegisterBuiltin("drawEllipseLines", builtinDrawEllipseLines)
	candy_evaluator.RegisterBuiltin("drawRingLines", builtinDrawRingLines)
	// rshapes — rectangle variants
	candy_evaluator.RegisterBuiltin("drawRectangleV", builtinDrawRectangleV)
	candy_evaluator.RegisterBuiltin("drawRectangleRec", builtinDrawRectangleRec)
	candy_evaluator.RegisterBuiltin("drawRectanglePro", builtinDrawRectanglePro)
	candy_evaluator.RegisterBuiltin("drawRectangleGradientV", builtinDrawRectangleGradientV)
	candy_evaluator.RegisterBuiltin("drawRectangleGradientH", builtinDrawRectangleGradientH)
	candy_evaluator.RegisterBuiltin("drawRectangleGradientEx", builtinDrawRectangleGradientEx)
	candy_evaluator.RegisterBuiltin("drawRectangleLinesEx", builtinDrawRectangleLinesEx)
	candy_evaluator.RegisterBuiltin("drawRectangleRoundedLines", builtinDrawRectangleRoundedLines)
	candy_evaluator.RegisterBuiltin("drawRectangleRoundedLinesEx", builtinDrawRectangleRoundedLinesEx)
	// rshapes — triangle/poly
	candy_evaluator.RegisterBuiltin("drawTriangleLines", builtinDrawTriangleLines)
	candy_evaluator.RegisterBuiltin("drawTriangleFan", builtinDrawTriangleFan)
	candy_evaluator.RegisterBuiltin("drawTriangleStrip", builtinDrawTriangleStrip)
	candy_evaluator.RegisterBuiltin("drawPoly", builtinDrawPoly)
	candy_evaluator.RegisterBuiltin("drawPolyLines", builtinDrawPolyLines)
	candy_evaluator.RegisterBuiltin("drawPolyLinesEx", builtinDrawPolyLinesEx)
	// rshapes — splines
	candy_evaluator.RegisterBuiltin("drawSplineLinear", builtinDrawSplineLinear)
	candy_evaluator.RegisterBuiltin("drawSplineBasis", builtinDrawSplineBasis)
	candy_evaluator.RegisterBuiltin("drawSplineCatmullRom", builtinDrawSplineCatmullRom)
	candy_evaluator.RegisterBuiltin("drawSplineBezierQuadratic", builtinDrawSplineBezierQuadratic)
	candy_evaluator.RegisterBuiltin("drawSplineBezierCubic", builtinDrawSplineBezierCubic)
	candy_evaluator.RegisterBuiltin("drawSplineSegmentLinear", builtinDrawSplineSegmentLinear)
	candy_evaluator.RegisterBuiltin("drawSplineSegmentBasis", builtinDrawSplineSegmentBasis)
	candy_evaluator.RegisterBuiltin("drawSplineSegmentCatmullRom", builtinDrawSplineSegmentCatmullRom)
	candy_evaluator.RegisterBuiltin("drawSplineSegmentBezierQuadratic", builtinDrawSplineSegmentBezierQuadratic)
	candy_evaluator.RegisterBuiltin("drawSplineSegmentBezierCubic", builtinDrawSplineSegmentBezierCubic)
	// rshapes — spline point eval
	candy_evaluator.RegisterBuiltin("getSplinePointLinear", builtinGetSplinePointLinear)
	candy_evaluator.RegisterBuiltin("getSplinePointBasis", builtinGetSplinePointBasis)
	candy_evaluator.RegisterBuiltin("getSplinePointCatmullRom", builtinGetSplinePointCatmullRom)
	candy_evaluator.RegisterBuiltin("getSplinePointBezierQuad", builtinGetSplinePointBezierQuad)
	candy_evaluator.RegisterBuiltin("getSplinePointBezierCubic", builtinGetSplinePointBezierCubic)
	// rshapes — collision extras
	candy_evaluator.RegisterBuiltin("checkCollisionCircleLine", builtinCheckCollisionCircleLine)
	candy_evaluator.RegisterBuiltin("checkCollisionPointRec", builtinCheckCollisionPointRec)
	candy_evaluator.RegisterBuiltin("checkCollisionPointCircle", builtinCheckCollisionPointCircle)
	candy_evaluator.RegisterBuiltin("checkCollisionPointTriangle", builtinCheckCollisionPointTriangle)
	candy_evaluator.RegisterBuiltin("checkCollisionPointLine", builtinCheckCollisionPointLine)
	candy_evaluator.RegisterBuiltin("checkCollisionPointPoly", builtinCheckCollisionPointPoly)
	candy_evaluator.RegisterBuiltin("checkCollisionLines", builtinCheckCollisionLines)
	candy_evaluator.RegisterBuiltin("getCollisionRec", builtinGetCollisionRec)

	// rtext
	candy_evaluator.RegisterBuiltin("drawText", builtinDrawText)
	candy_evaluator.RegisterBuiltin("text", builtinDrawText)
	candy_evaluator.RegisterBuiltin("measureText", builtinMeasureText)
	candy_evaluator.RegisterBuiltin("loadFont", builtinLoadFont)
	candy_evaluator.RegisterBuiltin("unloadFont", builtinUnloadFont)
	candy_evaluator.RegisterBuiltin("drawTextEx", builtinDrawTextEx)

	// rtext — font loading extras
	candy_evaluator.RegisterBuiltin("getFontDefault", builtinGetFontDefault)
	candy_evaluator.RegisterBuiltin("loadFontEx", builtinLoadFontEx)
	candy_evaluator.RegisterBuiltin("loadFontFromImage", builtinLoadFontFromImage)
	candy_evaluator.RegisterBuiltin("loadFontFromMemory", builtinLoadFontFromMemory)
	candy_evaluator.RegisterBuiltin("isFontValid", builtinIsFontValid)
	// rtext — drawing extras
	candy_evaluator.RegisterBuiltin("drawTextPro", builtinDrawTextPro)
	candy_evaluator.RegisterBuiltin("drawTextCodepoint", builtinDrawTextCodepoint)
	candy_evaluator.RegisterBuiltin("drawTextCodepoints", builtinDrawTextCodepoints)
	// rtext — metrics
	candy_evaluator.RegisterBuiltin("setTextLineSpacing", builtinSetTextLineSpacing)
	candy_evaluator.RegisterBuiltin("measureTextEx", builtinMeasureTextEx)
	candy_evaluator.RegisterBuiltin("getGlyphIndex", builtinGetGlyphIndex)
	candy_evaluator.RegisterBuiltin("getGlyphInfo", builtinGetGlyphInfo)
	candy_evaluator.RegisterBuiltin("getGlyphAtlasRec", builtinGetGlyphAtlasRec)
	// rtext — string utilities (Go-native)
	candy_evaluator.RegisterBuiltin("textIsEqual", builtinTextIsEqual)
	candy_evaluator.RegisterBuiltin("textLength", builtinTextLength)
	candy_evaluator.RegisterBuiltin("textSubtext", builtinTextSubtext)
	candy_evaluator.RegisterBuiltin("textRemoveSpaces", builtinTextRemoveSpaces)
	candy_evaluator.RegisterBuiltin("getTextBetween", builtinGetTextBetween)
	candy_evaluator.RegisterBuiltin("textReplace", builtinTextReplace)
	candy_evaluator.RegisterBuiltin("textInsert", builtinTextInsert)
	candy_evaluator.RegisterBuiltin("textJoin", builtinTextJoin)
	candy_evaluator.RegisterBuiltin("textSplit", builtinTextSplit)
	candy_evaluator.RegisterBuiltin("textFindIndex", builtinTextFindIndex)
	candy_evaluator.RegisterBuiltin("textToUpper", builtinTextToUpper)
	candy_evaluator.RegisterBuiltin("textToLower", builtinTextToLower)
	candy_evaluator.RegisterBuiltin("textToPascal", builtinTextToPascal)
	candy_evaluator.RegisterBuiltin("textToSnake", builtinTextToSnake)
	candy_evaluator.RegisterBuiltin("textToCamel", builtinTextToCamel)
	candy_evaluator.RegisterBuiltin("textToInteger", builtinTextToInteger)
	candy_evaluator.RegisterBuiltin("textToFloat", builtinTextToFloat)
	// rtext — codepoints (Go-native)
	candy_evaluator.RegisterBuiltin("getCodepointCount", builtinGetCodepointCount)
	candy_evaluator.RegisterBuiltin("loadCodepoints", builtinLoadCodepoints)
	candy_evaluator.RegisterBuiltin("codepointToUTF8", builtinCodepointToUTF8)
	candy_evaluator.RegisterBuiltin("loadUTF8", builtinLoadUTF8)
	candy_evaluator.RegisterBuiltin("loadTextLines", builtinLoadTextLines)

	// rtextures
	candy_evaluator.RegisterBuiltin("loadTexture", builtinLoadTexture)
	candy_evaluator.RegisterBuiltin("image", builtinImage)
	candy_evaluator.RegisterBuiltin("unloadTexture", builtinUnloadTexture)
	candy_evaluator.RegisterBuiltin("isTextureReady", builtinIsTextureReady)
	candy_evaluator.RegisterBuiltin("drawTexture", builtinDrawTexture)
	candy_evaluator.RegisterBuiltin("drawTextureEx", builtinDrawTextureEx)
	candy_evaluator.RegisterBuiltin("drawTextureRec", builtinDrawTextureRec)
	candy_evaluator.RegisterBuiltin("loadRenderTexture", builtinLoadRenderTexture)
	candy_evaluator.RegisterBuiltin("unloadRenderTexture", builtinUnloadRenderTexture)
	candy_evaluator.RegisterBuiltin("beginTextureMode", builtinBeginTextureMode)
	candy_evaluator.RegisterBuiltin("endTextureMode", builtinEndTextureMode)
	candy_evaluator.RegisterBuiltin("getRenderTextureTexture", builtinGetRenderTextureTexture)
	candy_evaluator.RegisterBuiltin("loadImage", builtinLoadImage)
	candy_evaluator.RegisterBuiltin("unloadImage", builtinUnloadImage)
	candy_evaluator.RegisterBuiltin("loadTextureFromImage", builtinLoadTextureFromImage)
	candy_evaluator.RegisterBuiltin("imageResize", builtinImageResize)
	candy_evaluator.RegisterBuiltin("imageColorTint", builtinImageColorTint)
	candy_evaluator.RegisterBuiltin("imageCrop", builtinImageCrop)
	candy_evaluator.RegisterBuiltin("imageFlipVertical", builtinImageFlipVertical)
	candy_evaluator.RegisterBuiltin("imageFlipHorizontal", builtinImageFlipHorizontal)
	candy_evaluator.RegisterBuiltin("imageRotate", builtinImageRotate)
	candy_evaluator.RegisterBuiltin("imageResizeCanvas", builtinImageResizeCanvas)
	candy_evaluator.RegisterBuiltin("imageAlphaCrop", builtinImageAlphaCrop)
	candy_evaluator.RegisterBuiltin("imageAlphaClear", builtinImageAlphaClear)
	candy_evaluator.RegisterBuiltin("imageAlphaMask", builtinImageAlphaMask)
	candy_evaluator.RegisterBuiltin("imageAlphaPremultiply", builtinImageAlphaPremultiply)
	candy_evaluator.RegisterBuiltin("imageBlurGaussian", builtinImageBlurGaussian)
	candy_evaluator.RegisterBuiltin("imageColorInvert", builtinImageColorInvert)
	candy_evaluator.RegisterBuiltin("imageColorGrayscale", builtinImageColorGrayscale)
	candy_evaluator.RegisterBuiltin("imageColorContrast", builtinImageColorContrast)
	candy_evaluator.RegisterBuiltin("imageColorBrightness", builtinImageColorBrightness)
	candy_evaluator.RegisterBuiltin("imageColorReplace", builtinImageColorReplace)
	candy_evaluator.RegisterBuiltin("imageMipmaps", builtinImageMipmaps)
	candy_evaluator.RegisterBuiltin("imageDither", builtinImageDither)
	candy_evaluator.RegisterBuiltin("imageCopy", builtinImageCopy)
	candy_evaluator.RegisterBuiltin("imageFromImage", builtinImageFromImage)
	candy_evaluator.RegisterBuiltin("imageDraw", builtinImageDraw)
	candy_evaluator.RegisterBuiltin("imageFormat", builtinImageFormat)
	candy_evaluator.RegisterBuiltin("imageToPOT", builtinImageToPOT)
	candy_evaluator.RegisterBuiltin("imageText", builtinImageText)
	candy_evaluator.RegisterBuiltin("imageTextEx", builtinImageTextEx)
	candy_evaluator.RegisterBuiltin("exportImage", builtinExportImage)
	candy_evaluator.RegisterBuiltin("genImageColor", builtinGenImageColor)
	candy_evaluator.RegisterBuiltin("genImageGradientLinear", builtinGenImageGradientLinear)
	candy_evaluator.RegisterBuiltin("genImageGradientRadial", builtinGenImageGradientRadial)
	candy_evaluator.RegisterBuiltin("genImageGradientSquare", builtinGenImageGradientSquare)
	candy_evaluator.RegisterBuiltin("genImageChecked", builtinGenImageChecked)
	candy_evaluator.RegisterBuiltin("genImageWhiteNoise", builtinGenImageWhiteNoise)
	candy_evaluator.RegisterBuiltin("genImagePerlinNoise", builtinGenImagePerlinNoise)
	candy_evaluator.RegisterBuiltin("genImageCellular", builtinGenImageCellular)
	candy_evaluator.RegisterBuiltin("genImageText", builtinGenImageText)
	// rtextures — image loading extras
	candy_evaluator.RegisterBuiltin("loadImageRaw", builtinLoadImageRaw)
	candy_evaluator.RegisterBuiltin("loadImageFromTexture", builtinLoadImageFromTexture)
	candy_evaluator.RegisterBuiltin("loadImageFromScreen", builtinLoadImageFromScreen)
	candy_evaluator.RegisterBuiltin("isImageValid", builtinIsImageValid)
	candy_evaluator.RegisterBuiltin("exportImageAsCode", builtinExportImageAsCode)
	candy_evaluator.RegisterBuiltin("exportImageToMemory", builtinExportImageToMemory)
	// rtextures — image manipulation extras
	candy_evaluator.RegisterBuiltin("imageFromChannel", builtinImageFromChannel)
	candy_evaluator.RegisterBuiltin("imageResizeNN", builtinImageResizeNN)
	candy_evaluator.RegisterBuiltin("imageKernelConvolution", builtinImageKernelConvolution)
	candy_evaluator.RegisterBuiltin("imageRotateCW", builtinImageRotateCW)
	candy_evaluator.RegisterBuiltin("imageRotateCCW", builtinImageRotateCCW)
	candy_evaluator.RegisterBuiltin("loadImageColors", builtinLoadImageColors)
	candy_evaluator.RegisterBuiltin("loadImagePalette", builtinLoadImagePalette)
	candy_evaluator.RegisterBuiltin("getImageAlphaBorder", builtinGetImageAlphaBorder)
	candy_evaluator.RegisterBuiltin("getImageColor", builtinGetImageColor)
	// rtextures — image drawing
	candy_evaluator.RegisterBuiltin("imageClearBackground", builtinImageClearBackground)
	candy_evaluator.RegisterBuiltin("imageDrawPixel", builtinImageDrawPixel)
	candy_evaluator.RegisterBuiltin("imageDrawPixelV", builtinImageDrawPixelV)
	candy_evaluator.RegisterBuiltin("imageDrawLine", builtinImageDrawLine)
	candy_evaluator.RegisterBuiltin("imageDrawLineV", builtinImageDrawLineV)
	candy_evaluator.RegisterBuiltin("imageDrawLineEx", builtinImageDrawLineEx)
	candy_evaluator.RegisterBuiltin("imageDrawCircle", builtinImageDrawCircle)
	candy_evaluator.RegisterBuiltin("imageDrawCircleV", builtinImageDrawCircleV)
	candy_evaluator.RegisterBuiltin("imageDrawCircleLines", builtinImageDrawCircleLines)
	candy_evaluator.RegisterBuiltin("imageDrawCircleLinesV", builtinImageDrawCircleLinesV)
	candy_evaluator.RegisterBuiltin("imageDrawRectangle", builtinImageDrawRectangle)
	candy_evaluator.RegisterBuiltin("imageDrawRectangleV", builtinImageDrawRectangleV)
	candy_evaluator.RegisterBuiltin("imageDrawRectangleRec", builtinImageDrawRectangleRec)
	candy_evaluator.RegisterBuiltin("imageDrawRectangleLines", builtinImageDrawRectangleLines)
	candy_evaluator.RegisterBuiltin("imageDrawTriangle", builtinImageDrawTriangle)
	candy_evaluator.RegisterBuiltin("imageDrawTriangleEx", builtinImageDrawTriangleEx)
	candy_evaluator.RegisterBuiltin("imageDrawTriangleLines", builtinImageDrawTriangleLines)
	candy_evaluator.RegisterBuiltin("imageDrawTriangleFan", builtinImageDrawTriangleFan)
	candy_evaluator.RegisterBuiltin("imageDrawTriangleStrip", builtinImageDrawTriangleStrip)
	candy_evaluator.RegisterBuiltin("imageDrawText", builtinImageDrawText)
	candy_evaluator.RegisterBuiltin("imageDrawTextEx", builtinImageDrawTextEx)
	// rtextures — texture extras
	candy_evaluator.RegisterBuiltin("loadTextureCubemap", builtinLoadTextureCubemap)
	candy_evaluator.RegisterBuiltin("isTextureValid", builtinIsTextureValid)
	candy_evaluator.RegisterBuiltin("isRenderTextureValid", builtinIsRenderTextureValid)
	candy_evaluator.RegisterBuiltin("genTextureMipmaps", builtinGenTextureMipmaps)
	candy_evaluator.RegisterBuiltin("setTextureFilter", builtinSetTextureFilter)
	candy_evaluator.RegisterBuiltin("setTextureWrap", builtinSetTextureWrap)
	candy_evaluator.RegisterBuiltin("drawTextureV", builtinDrawTextureV)
	candy_evaluator.RegisterBuiltin("drawTexturePro", builtinDrawTexturePro)
	candy_evaluator.RegisterBuiltin("drawTextureNPatch", builtinDrawTextureNPatch)
	// rtextures — color/pixel
	candy_evaluator.RegisterBuiltin("colorIsEqual", builtinColorIsEqual)
	candy_evaluator.RegisterBuiltin("fade", builtinFade)
	candy_evaluator.RegisterBuiltin("colorToInt", builtinColorToInt)
	candy_evaluator.RegisterBuiltin("colorNormalize", builtinColorNormalize)
	candy_evaluator.RegisterBuiltin("colorFromNormalized", builtinColorFromNormalized)
	candy_evaluator.RegisterBuiltin("colorToHSV", builtinColorToHSV)
	candy_evaluator.RegisterBuiltin("colorFromHSV", builtinColorFromHSV)
	candy_evaluator.RegisterBuiltin("colorTint", builtinColorTint)
	candy_evaluator.RegisterBuiltin("colorBrightness", builtinColorBrightness)
	candy_evaluator.RegisterBuiltin("colorContrast", builtinColorContrast)
	candy_evaluator.RegisterBuiltin("colorAlpha", builtinColorAlpha)
	candy_evaluator.RegisterBuiltin("colorAlphaBlend", builtinColorAlphaBlend)
	candy_evaluator.RegisterBuiltin("colorLerp", builtinColorLerp)
	candy_evaluator.RegisterBuiltin("getColor", builtinGetColor)
	candy_evaluator.RegisterBuiltin("getPixelDataSize", builtinGetPixelDataSize)

	// rshaders
	candy_evaluator.RegisterBuiltin("loadShader", builtinLoadShader)
	candy_evaluator.RegisterBuiltin("unloadShader", builtinUnloadShader)
	candy_evaluator.RegisterBuiltin("beginShaderMode", builtinBeginShaderMode)
	candy_evaluator.RegisterBuiltin("endShaderMode", builtinEndShaderMode)

	// rmodels
	candy_evaluator.RegisterBuiltin("beginMode3D", builtinBeginMode3D)
	candy_evaluator.RegisterBuiltin("endMode3D", builtinEndMode3D)
	candy_evaluator.RegisterBuiltin("drawCube", builtinDrawCube)
	candy_evaluator.RegisterBuiltin("drawCubeWires", builtinDrawCubeWires)
	candy_evaluator.RegisterBuiltin("drawPlane", builtinDrawPlane)
	candy_evaluator.RegisterBuiltin("drawSphere", builtinDrawSphere)
	candy_evaluator.RegisterBuiltin("drawSphereEx", builtinDrawSphereEx)
	candy_evaluator.RegisterBuiltin("drawSphereWires", builtinDrawSphereWires)
	candy_evaluator.RegisterBuiltin("drawCylinder", builtinDrawCylinder)
	candy_evaluator.RegisterBuiltin("drawCylinderEx", builtinDrawCylinderEx)
	candy_evaluator.RegisterBuiltin("drawCylinderWires", builtinDrawCylinderWires)
	candy_evaluator.RegisterBuiltin("drawLine3D", builtinDrawLine3D)
	candy_evaluator.RegisterBuiltin("drawRay", builtinDrawRay)
	candy_evaluator.RegisterBuiltin("drawBoundingBox", builtinDrawBoundingBox)
	candy_evaluator.RegisterBuiltin("drawCapsule", builtinDrawCapsule)
	candy_evaluator.RegisterBuiltin("drawCapsuleWires", builtinDrawCapsuleWires)
	candy_evaluator.RegisterBuiltin("drawGrid", builtinDrawGrid)
	candy_evaluator.RegisterBuiltin("getMouseRay", builtinGetMouseRay)
	candy_evaluator.RegisterBuiltin("getRayCollisionBox", builtinGetRayCollisionBox)
	candy_evaluator.RegisterBuiltin("getRayCollisionSphere", builtinGetRayCollisionSphere)
	candy_evaluator.RegisterBuiltin("checkCollisionBoxes", builtinCheckCollisionBoxes)
	candy_evaluator.RegisterBuiltin("checkCollisionSpheres", builtinCheckCollisionSpheres)
	candy_evaluator.RegisterBuiltin("loadModel", builtinLoadModel)
	candy_evaluator.RegisterBuiltin("unloadModel", builtinUnloadModel)
	candy_evaluator.RegisterBuiltin("drawModel", builtinDrawModel)
	candy_evaluator.RegisterBuiltin("drawModelEx", builtinDrawModelEx)
	candy_evaluator.RegisterBuiltin("drawModelWires", builtinDrawModelWires)
	candy_evaluator.RegisterBuiltin("drawModelWiresEx", builtinDrawModelWiresEx)
	candy_evaluator.RegisterBuiltin("drawModelPoints", builtinDrawModelPoints)
	candy_evaluator.RegisterBuiltin("drawModelPointsEx", builtinDrawModelPointsEx)
	candy_evaluator.RegisterBuiltin("drawBillboard", builtinDrawBillboard)
	candy_evaluator.RegisterBuiltin("drawBillboardRec", builtinDrawBillboardRec)
	candy_evaluator.RegisterBuiltin("drawBillboardPro", builtinDrawBillboardPro)
	candy_evaluator.RegisterBuiltin("loadModelAnimations", builtinLoadModelAnimations)
	candy_evaluator.RegisterBuiltin("updateModelAnimation", builtinUpdateModelAnimation)
	// rmodels extras — basic 3D drawing
	candy_evaluator.RegisterBuiltin("drawPoint3D", builtinDrawPoint3D)
	candy_evaluator.RegisterBuiltin("drawCircle3D", builtinDrawCircle3D)
	candy_evaluator.RegisterBuiltin("drawTriangle3D", builtinDrawTriangle3D)
	candy_evaluator.RegisterBuiltin("drawCubeV", builtinDrawCubeV)
	candy_evaluator.RegisterBuiltin("drawCubeWiresV", builtinDrawCubeWiresV)
	candy_evaluator.RegisterBuiltin("drawCylinderWiresEx", builtinDrawCylinderWiresEx)
	// rmodels extras — model
	candy_evaluator.RegisterBuiltin("isModelValid", builtinIsModelValid)
	candy_evaluator.RegisterBuiltin("getModelBoundingBox", builtinGetModelBoundingBox)
	candy_evaluator.RegisterBuiltin("loadModelFromMesh", builtinLoadModelFromMesh)
	// rmodels extras — mesh management
	candy_evaluator.RegisterBuiltin("getMeshBoundingBox", builtinGetMeshBoundingBox)
	candy_evaluator.RegisterBuiltin("unloadMesh", builtinUnloadMesh)
	candy_evaluator.RegisterBuiltin("exportMesh", builtinExportMesh)
	candy_evaluator.RegisterBuiltin("updateMeshBuffer", builtinUpdateMeshBuffer)
	candy_evaluator.RegisterBuiltin("drawMesh", builtinDrawMesh)
	// rmodels extras — mesh generation
	candy_evaluator.RegisterBuiltin("genMeshPoly", builtinGenMeshPoly)
	candy_evaluator.RegisterBuiltin("genMeshPlane", builtinGenMeshPlane)
	candy_evaluator.RegisterBuiltin("genMeshCube", builtinGenMeshCube)
	candy_evaluator.RegisterBuiltin("genMeshSphere", builtinGenMeshSphere)
	candy_evaluator.RegisterBuiltin("genMeshHemiSphere", builtinGenMeshHemiSphere)
	candy_evaluator.RegisterBuiltin("genMeshCylinder", builtinGenMeshCylinder)
	candy_evaluator.RegisterBuiltin("genMeshCone", builtinGenMeshCone)
	candy_evaluator.RegisterBuiltin("genMeshTorus", builtinGenMeshTorus)
	candy_evaluator.RegisterBuiltin("genMeshKnot", builtinGenMeshKnot)
	candy_evaluator.RegisterBuiltin("genMeshHeightmap", builtinGenMeshHeightmap)
	candy_evaluator.RegisterBuiltin("genMeshCubicmap", builtinGenMeshCubicmap)
	// rmodels extras — material management
	candy_evaluator.RegisterBuiltin("loadMaterials", builtinLoadMaterials)
	candy_evaluator.RegisterBuiltin("loadMaterialDefault", builtinLoadMaterialDefault)
	candy_evaluator.RegisterBuiltin("isMaterialValid", builtinIsMaterialValid)
	candy_evaluator.RegisterBuiltin("unloadMaterial", builtinUnloadMaterial)
	candy_evaluator.RegisterBuiltin("setMaterialTexture", builtinSetMaterialTexture)
	candy_evaluator.RegisterBuiltin("setModelMeshMaterial", builtinSetModelMeshMaterial)
	// rmodels extras — animation
	candy_evaluator.RegisterBuiltin("updateModelAnimationBones", builtinUpdateModelAnimationBones)
	candy_evaluator.RegisterBuiltin("unloadModelAnimations", builtinUnloadModelAnimations)
	candy_evaluator.RegisterBuiltin("isModelAnimationValid", builtinIsModelAnimationValid)
	// rmodels extras — collision
	candy_evaluator.RegisterBuiltin("checkCollisionBoxSphere", builtinCheckCollisionBoxSphere)
	candy_evaluator.RegisterBuiltin("getRayCollisionMesh", builtinGetRayCollisionMesh)
	candy_evaluator.RegisterBuiltin("getRayCollisionTriangle", builtinGetRayCollisionTriangle)
	candy_evaluator.RegisterBuiltin("getRayCollisionQuad", builtinGetRayCollisionQuad)

	// raudio
	candy_evaluator.RegisterBuiltin("initAudioDevice", builtinInitAudioDevice)
	candy_evaluator.RegisterBuiltin("closeAudioDevice", builtinCloseAudioDevice)
	candy_evaluator.RegisterBuiltin("loadSound", builtinLoadSound)
	candy_evaluator.RegisterBuiltin("unloadSound", builtinUnloadSound)
	candy_evaluator.RegisterBuiltin("playSound", builtinPlaySound)
	candy_evaluator.RegisterBuiltin("stopSound", builtinStopSound)
	candy_evaluator.RegisterBuiltin("isSoundPlaying", builtinIsSoundPlaying)
	candy_evaluator.RegisterBuiltin("setSoundVolume", builtinSetSoundVolume)
	candy_evaluator.RegisterBuiltin("loadMusicStream", builtinLoadMusicStream)
	candy_evaluator.RegisterBuiltin("unloadMusicStream", builtinUnloadMusicStream)
	candy_evaluator.RegisterBuiltin("playMusicStream", builtinPlayMusicStream)
	candy_evaluator.RegisterBuiltin("updateMusicStream", builtinUpdateMusicStream)
	candy_evaluator.RegisterBuiltin("stopMusicStream", builtinStopMusicStream)
	candy_evaluator.RegisterBuiltin("setMusicVolume", builtinSetMusicVolume)
	candy_evaluator.RegisterBuiltin("beep", builtinBeep)
	// raudio extras — device
	candy_evaluator.RegisterBuiltin("isAudioDeviceReady", builtinIsAudioDeviceReady)
	candy_evaluator.RegisterBuiltin("setMasterVolume", builtinSetMasterVolume)
	candy_evaluator.RegisterBuiltin("getMasterVolume", builtinGetMasterVolume)
	// raudio extras — wave loading
	candy_evaluator.RegisterBuiltin("loadWave", builtinLoadWave)
	candy_evaluator.RegisterBuiltin("loadWaveFromMemory", builtinLoadWaveFromMemory)
	candy_evaluator.RegisterBuiltin("isWaveValid", builtinIsWaveValid)
	candy_evaluator.RegisterBuiltin("unloadWave", builtinUnloadWave)
	candy_evaluator.RegisterBuiltin("exportWave", builtinExportWave)
	// raudio extras — sound
	candy_evaluator.RegisterBuiltin("loadSoundFromWave", builtinLoadSoundFromWave)
	candy_evaluator.RegisterBuiltin("loadSoundAlias", builtinLoadSoundAlias)
	candy_evaluator.RegisterBuiltin("isSoundValid", builtinIsSoundValid)
	candy_evaluator.RegisterBuiltin("unloadSoundAlias", builtinUnloadSoundAlias)
	candy_evaluator.RegisterBuiltin("pauseSound", builtinPauseSound)
	candy_evaluator.RegisterBuiltin("resumeSound", builtinResumeSound)
	candy_evaluator.RegisterBuiltin("setSoundPitch", builtinSetSoundPitch)
	candy_evaluator.RegisterBuiltin("setSoundPan", builtinSetSoundPan)
	// raudio extras — wave management
	candy_evaluator.RegisterBuiltin("waveCopy", builtinWaveCopy)
	candy_evaluator.RegisterBuiltin("waveCrop", builtinWaveCrop)
	candy_evaluator.RegisterBuiltin("waveFormat", builtinWaveFormat)
	candy_evaluator.RegisterBuiltin("loadWaveSamples", builtinLoadWaveSamples)
	// raudio extras — music
	candy_evaluator.RegisterBuiltin("loadMusicStreamFromMemory", builtinLoadMusicStreamFromMemory)
	candy_evaluator.RegisterBuiltin("isMusicValid", builtinIsMusicValid)
	candy_evaluator.RegisterBuiltin("isMusicStreamPlaying", builtinIsMusicStreamPlaying)
	candy_evaluator.RegisterBuiltin("pauseMusicStream", builtinPauseMusicStream)
	candy_evaluator.RegisterBuiltin("resumeMusicStream", builtinResumeMusicStream)
	candy_evaluator.RegisterBuiltin("seekMusicStream", builtinSeekMusicStream)
	candy_evaluator.RegisterBuiltin("setMusicPitch", builtinSetMusicPitch)
	candy_evaluator.RegisterBuiltin("setMusicPan", builtinSetMusicPan)
	candy_evaluator.RegisterBuiltin("getMusicTimeLength", builtinGetMusicTimeLength)
	candy_evaluator.RegisterBuiltin("getMusicTimePlayed", builtinGetMusicTimePlayed)
	// raudio extras — audio stream
	candy_evaluator.RegisterBuiltin("loadAudioStream", builtinLoadAudioStream)
	candy_evaluator.RegisterBuiltin("isAudioStreamValid", builtinIsAudioStreamValid)
	candy_evaluator.RegisterBuiltin("unloadAudioStream", builtinUnloadAudioStream)
	candy_evaluator.RegisterBuiltin("updateAudioStream", builtinUpdateAudioStream)
	candy_evaluator.RegisterBuiltin("isAudioStreamProcessed", builtinIsAudioStreamProcessed)
	candy_evaluator.RegisterBuiltin("playAudioStream", builtinPlayAudioStream)
	candy_evaluator.RegisterBuiltin("pauseAudioStream", builtinPauseAudioStream)
	candy_evaluator.RegisterBuiltin("resumeAudioStream", builtinResumeAudioStream)
	candy_evaluator.RegisterBuiltin("isAudioStreamPlaying", builtinIsAudioStreamPlaying)
	candy_evaluator.RegisterBuiltin("stopAudioStream", builtinStopAudioStream)
	candy_evaluator.RegisterBuiltin("setAudioStreamVolume", builtinSetAudioStreamVolume)
	candy_evaluator.RegisterBuiltin("setAudioStreamPitch", builtinSetAudioStreamPitch)
	candy_evaluator.RegisterBuiltin("setAudioStreamPan", builtinSetAudioStreamPan)
	candy_evaluator.RegisterBuiltin("setAudioStreamBufferSizeDefault", builtinSetAudioStreamBufferSizeDefault)

	// camera
	candy_evaluator.RegisterBuiltin("beginMode2D", builtinBeginMode2D)
	candy_evaluator.RegisterBuiltin("endMode2D", builtinEndMode2D)
	candy_evaluator.RegisterBuiltin("beginVrSimulatorMode", builtinBeginVrSimulatorMode)
	candy_evaluator.RegisterBuiltin("endVrSimulatorMode", builtinEndVrSimulatorMode)

	// rstructs — constructors
	candy_evaluator.RegisterBuiltin("vec2", builtinVec2)
	candy_evaluator.RegisterBuiltin("vec3", builtinVec3)
	candy_evaluator.RegisterBuiltin("vec4", builtinVec4)
	candy_evaluator.RegisterBuiltin("rect", builtinRect)
	candy_evaluator.RegisterBuiltin("color", builtinColor)
	candy_evaluator.RegisterBuiltin("boundingBox", builtinBoundingBox)
	candy_evaluator.RegisterBuiltin("ray", builtinRay)
	candy_evaluator.RegisterBuiltin("camera3D", builtinCamera3D)
	candy_evaluator.RegisterBuiltin("camera2D", builtinCamera2D)
	candy_evaluator.RegisterBuiltin("getNamedColor", builtinGetNamedColor)
	// rstructs — named colors
	candy_evaluator.RegisterBuiltin("COLOR_LIGHTGRAY", builtinColorLightGray)
	candy_evaluator.RegisterBuiltin("COLOR_GRAY", builtinColorGray)
	candy_evaluator.RegisterBuiltin("COLOR_DARKGRAY", builtinColorDarkGray)
	candy_evaluator.RegisterBuiltin("COLOR_YELLOW", builtinColorYellow)
	candy_evaluator.RegisterBuiltin("COLOR_GOLD", builtinColorGold)
	candy_evaluator.RegisterBuiltin("COLOR_ORANGE", builtinColorOrange)
	candy_evaluator.RegisterBuiltin("COLOR_PINK", builtinColorPink)
	candy_evaluator.RegisterBuiltin("COLOR_RED", builtinColorRed)
	candy_evaluator.RegisterBuiltin("COLOR_MAROON", builtinColorMaroon)
	candy_evaluator.RegisterBuiltin("COLOR_GREEN", builtinColorGreen)
	candy_evaluator.RegisterBuiltin("COLOR_LIME", builtinColorLime)
	candy_evaluator.RegisterBuiltin("COLOR_DARKGREEN", builtinColorDarkGreen)
	candy_evaluator.RegisterBuiltin("COLOR_SKYBLUE", builtinColorSkyBlue)
	candy_evaluator.RegisterBuiltin("COLOR_BLUE", builtinColorBlue)
	candy_evaluator.RegisterBuiltin("COLOR_DARKBLUE", builtinColorDarkBlue)
	candy_evaluator.RegisterBuiltin("COLOR_PURPLE", builtinColorPurple)
	candy_evaluator.RegisterBuiltin("COLOR_VIOLET", builtinColorViolet)
	candy_evaluator.RegisterBuiltin("COLOR_DARKPURPLE", builtinColorDarkPurple)
	candy_evaluator.RegisterBuiltin("COLOR_BEIGE", builtinColorBeige)
	candy_evaluator.RegisterBuiltin("COLOR_BROWN", builtinColorBrown)
	candy_evaluator.RegisterBuiltin("COLOR_DARKBROWN", builtinColorDarkBrown)
	candy_evaluator.RegisterBuiltin("COLOR_WHITE", builtinColorWhite)
	candy_evaluator.RegisterBuiltin("COLOR_BLACK", builtinColorBlack)
	candy_evaluator.RegisterBuiltin("COLOR_BLANK", builtinColorBlank)
	candy_evaluator.RegisterBuiltin("COLOR_MAGENTA", builtinColorMagenta)
	candy_evaluator.RegisterBuiltin("COLOR_RAYWHITE", builtinColorRayWhite)

	// raymath — utils
	candy_evaluator.RegisterBuiltin("mathClamp", builtinMathClamp)
	candy_evaluator.RegisterBuiltin("mathLerp", builtinMathLerp)
	candy_evaluator.RegisterBuiltin("mathNormalize", builtinMathNormalize)
	candy_evaluator.RegisterBuiltin("mathRemap", builtinMathRemap)
	candy_evaluator.RegisterBuiltin("mathWrap", builtinMathWrap)
	candy_evaluator.RegisterBuiltin("floatEquals", builtinFloatEquals)
	// raymath — Vector2
	candy_evaluator.RegisterBuiltin("vector2Zero", builtinVector2Zero)
	candy_evaluator.RegisterBuiltin("vector2One", builtinVector2One)
	candy_evaluator.RegisterBuiltin("vector2Add", builtinVector2Add)
	candy_evaluator.RegisterBuiltin("vector2AddValue", builtinVector2AddValue)
	candy_evaluator.RegisterBuiltin("vector2Subtract", builtinVector2Subtract)
	candy_evaluator.RegisterBuiltin("vector2SubtractValue", builtinVector2SubtractValue)
	candy_evaluator.RegisterBuiltin("vector2Length", builtinVector2Length)
	candy_evaluator.RegisterBuiltin("vector2LengthSqr", builtinVector2LengthSqr)
	candy_evaluator.RegisterBuiltin("vector2DotProduct", builtinVector2DotProduct)
	candy_evaluator.RegisterBuiltin("vector2CrossProduct", builtinVector2CrossProduct)
	candy_evaluator.RegisterBuiltin("vector2Distance", builtinVector2Distance)
	candy_evaluator.RegisterBuiltin("vector2DistanceSqr", builtinVector2DistanceSqr)
	candy_evaluator.RegisterBuiltin("vector2Angle", builtinVector2Angle)
	candy_evaluator.RegisterBuiltin("vector2LineAngle", builtinVector2LineAngle)
	candy_evaluator.RegisterBuiltin("vector2Scale", builtinVector2Scale)
	candy_evaluator.RegisterBuiltin("vector2Multiply", builtinVector2Multiply)
	candy_evaluator.RegisterBuiltin("vector2Negate", builtinVector2Negate)
	candy_evaluator.RegisterBuiltin("vector2Divide", builtinVector2Divide)
	candy_evaluator.RegisterBuiltin("vector2Normalize", builtinVector2Normalize)
	candy_evaluator.RegisterBuiltin("vector2Transform", builtinVector2Transform)
	candy_evaluator.RegisterBuiltin("vector2Lerp", builtinVector2Lerp)
	candy_evaluator.RegisterBuiltin("vector2Reflect", builtinVector2Reflect)
	candy_evaluator.RegisterBuiltin("vector2Rotate", builtinVector2Rotate)
	candy_evaluator.RegisterBuiltin("vector2MoveTowards", builtinVector2MoveTowards)
	candy_evaluator.RegisterBuiltin("vector2Invert", builtinVector2Invert)
	candy_evaluator.RegisterBuiltin("vector2Clamp", builtinVector2Clamp)
	candy_evaluator.RegisterBuiltin("vector2ClampValue", builtinVector2ClampValue)
	candy_evaluator.RegisterBuiltin("vector2Equals", builtinVector2Equals)
	// raymath — Vector3
	candy_evaluator.RegisterBuiltin("vector3Zero", builtinVector3Zero)
	candy_evaluator.RegisterBuiltin("vector3One", builtinVector3One)
	candy_evaluator.RegisterBuiltin("vector3Add", builtinVector3Add)
	candy_evaluator.RegisterBuiltin("vector3AddValue", builtinVector3AddValue)
	candy_evaluator.RegisterBuiltin("vector3Subtract", builtinVector3Subtract)
	candy_evaluator.RegisterBuiltin("vector3SubtractValue", builtinVector3SubtractValue)
	candy_evaluator.RegisterBuiltin("vector3Scale", builtinVector3Scale)
	candy_evaluator.RegisterBuiltin("vector3Multiply", builtinVector3Multiply)
	candy_evaluator.RegisterBuiltin("vector3CrossProduct", builtinVector3CrossProduct)
	candy_evaluator.RegisterBuiltin("vector3Perpendicular", builtinVector3Perpendicular)
	candy_evaluator.RegisterBuiltin("vector3Length", builtinVector3Length)
	candy_evaluator.RegisterBuiltin("vector3LengthSqr", builtinVector3LengthSqr)
	candy_evaluator.RegisterBuiltin("vector3DotProduct", builtinVector3DotProduct)
	candy_evaluator.RegisterBuiltin("vector3Distance", builtinVector3Distance)
	candy_evaluator.RegisterBuiltin("vector3DistanceSqr", builtinVector3DistanceSqr)
	candy_evaluator.RegisterBuiltin("vector3Angle", builtinVector3Angle)
	candy_evaluator.RegisterBuiltin("vector3Negate", builtinVector3Negate)
	candy_evaluator.RegisterBuiltin("vector3Divide", builtinVector3Divide)
	candy_evaluator.RegisterBuiltin("vector3Normalize", builtinVector3Normalize)
	candy_evaluator.RegisterBuiltin("vector3Project", builtinVector3Project)
	candy_evaluator.RegisterBuiltin("vector3Reject", builtinVector3Reject)
	candy_evaluator.RegisterBuiltin("vector3Transform", builtinVector3Transform)
	candy_evaluator.RegisterBuiltin("vector3RotateByQuaternion", builtinVector3RotateByQuaternion)
	candy_evaluator.RegisterBuiltin("vector3RotateByAxisAngle", builtinVector3RotateByAxisAngle)
	candy_evaluator.RegisterBuiltin("vector3Lerp", builtinVector3Lerp)
	candy_evaluator.RegisterBuiltin("vector3Reflect", builtinVector3Reflect)
	candy_evaluator.RegisterBuiltin("vector3Min", builtinVector3Min)
	candy_evaluator.RegisterBuiltin("vector3Max", builtinVector3Max)
	candy_evaluator.RegisterBuiltin("vector3Barycenter", builtinVector3Barycenter)
	candy_evaluator.RegisterBuiltin("vector3Unproject", builtinVector3Unproject)
	candy_evaluator.RegisterBuiltin("vector3Invert", builtinVector3Invert)
	candy_evaluator.RegisterBuiltin("vector3Clamp", builtinVector3Clamp)
	candy_evaluator.RegisterBuiltin("vector3ClampValue", builtinVector3ClampValue)
	candy_evaluator.RegisterBuiltin("vector3Equals", builtinVector3Equals)
	candy_evaluator.RegisterBuiltin("vector3Refract", builtinVector3Refract)
	// raymath — Matrix
	candy_evaluator.RegisterBuiltin("matrixDeterminant", builtinMatrixDeterminant)
	candy_evaluator.RegisterBuiltin("matrixTrace", builtinMatrixTrace)
	candy_evaluator.RegisterBuiltin("matrixTranspose", builtinMatrixTranspose)
	candy_evaluator.RegisterBuiltin("matrixInvert", builtinMatrixInvert)
	candy_evaluator.RegisterBuiltin("matrixIdentity", builtinMatrixIdentity)
	candy_evaluator.RegisterBuiltin("matrixAdd", builtinMatrixAdd)
	candy_evaluator.RegisterBuiltin("matrixSubtract", builtinMatrixSubtract)
	candy_evaluator.RegisterBuiltin("matrixMultiply", builtinMatrixMultiply)
	candy_evaluator.RegisterBuiltin("matrixTranslate", builtinMatrixTranslate)
	candy_evaluator.RegisterBuiltin("matrixRotate", builtinMatrixRotate)
	candy_evaluator.RegisterBuiltin("matrixRotateX", builtinMatrixRotateX)
	candy_evaluator.RegisterBuiltin("matrixRotateY", builtinMatrixRotateY)
	candy_evaluator.RegisterBuiltin("matrixRotateZ", builtinMatrixRotateZ)
	candy_evaluator.RegisterBuiltin("matrixRotateXYZ", builtinMatrixRotateXYZ)
	candy_evaluator.RegisterBuiltin("matrixRotateZYX", builtinMatrixRotateZYX)
	candy_evaluator.RegisterBuiltin("matrixScale", builtinMatrixScale)
	candy_evaluator.RegisterBuiltin("matrixFrustum", builtinMatrixFrustum)
	candy_evaluator.RegisterBuiltin("matrixPerspective", builtinMatrixPerspective)
	candy_evaluator.RegisterBuiltin("matrixOrtho", builtinMatrixOrtho)
	candy_evaluator.RegisterBuiltin("matrixLookAt", builtinMatrixLookAt)
	candy_evaluator.RegisterBuiltin("matrixDecompose", builtinMatrixDecompose)
	// raymath — Quaternion
	candy_evaluator.RegisterBuiltin("quaternionAdd", builtinQuaternionAdd)
	candy_evaluator.RegisterBuiltin("quaternionAddValue", builtinQuaternionAddValue)
	candy_evaluator.RegisterBuiltin("quaternionSubtract", builtinQuaternionSubtract)
	candy_evaluator.RegisterBuiltin("quaternionSubtractValue", builtinQuaternionSubtractValue)
	candy_evaluator.RegisterBuiltin("quaternionIdentity", builtinQuaternionIdentity)
	candy_evaluator.RegisterBuiltin("quaternionLength", builtinQuaternionLength)
	candy_evaluator.RegisterBuiltin("quaternionNormalize", builtinQuaternionNormalize)
	candy_evaluator.RegisterBuiltin("quaternionInvert", builtinQuaternionInvert)
	candy_evaluator.RegisterBuiltin("quaternionMultiply", builtinQuaternionMultiply)
	candy_evaluator.RegisterBuiltin("quaternionScale", builtinQuaternionScale)
	candy_evaluator.RegisterBuiltin("quaternionDivide", builtinQuaternionDivide)
	candy_evaluator.RegisterBuiltin("quaternionLerp", builtinQuaternionLerp)
	candy_evaluator.RegisterBuiltin("quaternionNlerp", builtinQuaternionNlerp)
	candy_evaluator.RegisterBuiltin("quaternionSlerp", builtinQuaternionSlerp)
	candy_evaluator.RegisterBuiltin("quaternionFromVector3ToVector3", builtinQuaternionFromVector3ToVector3)
	candy_evaluator.RegisterBuiltin("quaternionFromMatrix", builtinQuaternionFromMatrix)
	candy_evaluator.RegisterBuiltin("quaternionToMatrix", builtinQuaternionToMatrix)
	candy_evaluator.RegisterBuiltin("quaternionFromAxisAngle", builtinQuaternionFromAxisAngle)
	candy_evaluator.RegisterBuiltin("quaternionToAxisAngle", builtinQuaternionToAxisAngle)
	candy_evaluator.RegisterBuiltin("quaternionFromEuler", builtinQuaternionFromEuler)
	candy_evaluator.RegisterBuiltin("quaternionToEuler", builtinQuaternionToEuler)
	candy_evaluator.RegisterBuiltin("quaternionTransform", builtinQuaternionTransform)
	candy_evaluator.RegisterBuiltin("quaternionEquals", builtinQuaternionEquals)

	// reasing
	candy_evaluator.RegisterBuiltin("easeLinear", builtinEaseLinear)
	candy_evaluator.RegisterBuiltin("easeSineIn", builtinEaseSineIn)
	candy_evaluator.RegisterBuiltin("easeSineOut", builtinEaseSineOut)
	candy_evaluator.RegisterBuiltin("easeSineInOut", builtinEaseSineInOut)
	candy_evaluator.RegisterBuiltin("easeCubicIn", builtinEaseCubicIn)
	candy_evaluator.RegisterBuiltin("easeCubicOut", builtinEaseCubicOut)
	candy_evaluator.RegisterBuiltin("easeBounceOut", builtinEaseBounceOut)

	// Game-helper layer overlays friendly aliases and high-level helpers.
	registerGameHelperBuiltins()

	// raygui — immediate-mode GUI
	candy_evaluator.RegisterBuiltin("guiEnable", builtinGuiEnable)
	candy_evaluator.RegisterBuiltin("guiDisable", builtinGuiDisable)
	candy_evaluator.RegisterBuiltin("guiLock", builtinGuiLock)
	candy_evaluator.RegisterBuiltin("guiUnlock", builtinGuiUnlock)
	candy_evaluator.RegisterBuiltin("guiIsLocked", builtinGuiIsLocked)
	candy_evaluator.RegisterBuiltin("guiSetAlpha", builtinGuiSetAlpha)
	candy_evaluator.RegisterBuiltin("guiSetState", builtinGuiSetState)
	candy_evaluator.RegisterBuiltin("guiGetState", builtinGuiGetState)
	candy_evaluator.RegisterBuiltin("guiSetFont", builtinGuiSetFont)
	candy_evaluator.RegisterBuiltin("guiGetFont", builtinGuiGetFont)
	candy_evaluator.RegisterBuiltin("guiSetStyle", builtinGuiSetStyle)
	candy_evaluator.RegisterBuiltin("guiGetStyle", builtinGuiGetStyle)
	candy_evaluator.RegisterBuiltin("guiLoadStyle", builtinGuiLoadStyle)
	candy_evaluator.RegisterBuiltin("guiLoadStyleDefault", builtinGuiLoadStyleDefault)
	candy_evaluator.RegisterBuiltin("guiSetTooltip", builtinGuiSetTooltip)
	candy_evaluator.RegisterBuiltin("guiEnableTooltip", builtinGuiEnableTooltip)
	candy_evaluator.RegisterBuiltin("guiDisableTooltip", builtinGuiDisableTooltip)
	candy_evaluator.RegisterBuiltin("guiSetIconScale", builtinGuiSetIconScale)
	// raygui — controls
	candy_evaluator.RegisterBuiltin("guiLabel", builtinGuiLabel)
	candy_evaluator.RegisterBuiltin("guiButton", builtinGuiButton)
	candy_evaluator.RegisterBuiltin("guiLabelButton", builtinGuiLabelButton)
	candy_evaluator.RegisterBuiltin("guiToggle", builtinGuiToggle)
	candy_evaluator.RegisterBuiltin("guiToggleGroup", builtinGuiToggleGroup)
	candy_evaluator.RegisterBuiltin("guiToggleSlider", builtinGuiToggleSlider)
	candy_evaluator.RegisterBuiltin("guiCheckBox", builtinGuiCheckBox)
	candy_evaluator.RegisterBuiltin("guiComboBox", builtinGuiComboBox)
	candy_evaluator.RegisterBuiltin("guiDropdownBox", builtinGuiDropdownBox)
	candy_evaluator.RegisterBuiltin("guiNewActive", builtinGuiNewActive)
	candy_evaluator.RegisterBuiltin("guiGetActive", builtinGuiGetActive)
	candy_evaluator.RegisterBuiltin("guiSetActive", builtinGuiSetActive)
	candy_evaluator.RegisterBuiltin("guiSlider", builtinGuiSlider)
	candy_evaluator.RegisterBuiltin("guiSliderBar", builtinGuiSliderBar)
	candy_evaluator.RegisterBuiltin("guiProgressBar", builtinGuiProgressBar)
	candy_evaluator.RegisterBuiltin("guiScrollBar", builtinGuiScrollBar)
	candy_evaluator.RegisterBuiltin("guiSpinner", builtinGuiSpinner)
	candy_evaluator.RegisterBuiltin("guiValueBox", builtinGuiValueBox)
	// raygui — text input
	candy_evaluator.RegisterBuiltin("guiNewTextBox", builtinGuiNewTextBox)
	candy_evaluator.RegisterBuiltin("guiGetText", builtinGuiGetText)
	candy_evaluator.RegisterBuiltin("guiSetText", builtinGuiSetText)
	candy_evaluator.RegisterBuiltin("guiTextBox", builtinGuiTextBox)
	// raygui — containers / layout
	// BlitzBasic 3D aliases
	candy_evaluator.RegisterBuiltin("Graphics3D", builtinGraphics3D)
	candy_evaluator.RegisterBuiltin("CreateCamera", builtinCreateCamera)
	candy_evaluator.RegisterBuiltin("CreateLight", builtinCreateLight)
	candy_evaluator.RegisterBuiltin("CreateCube", builtinCreateCube)
	candy_evaluator.RegisterBuiltin("CreateSphere", builtinCreateSphere)
	candy_evaluator.RegisterBuiltin("LoadMesh", builtinLoadMesh)
	candy_evaluator.RegisterBuiltin("PositionEntity", builtinPositionEntity)
	candy_evaluator.RegisterBuiltin("RotateEntity", builtinRotateEntity)
	candy_evaluator.RegisterBuiltin("ScaleEntity", builtinScaleEntity)
	candy_evaluator.RegisterBuiltin("MoveEntity", builtinMoveEntity)
	candy_evaluator.RegisterBuiltin("TurnEntity", builtinTurnEntity)
	candy_evaluator.RegisterBuiltin("EntityX", builtinEntityX)
	candy_evaluator.RegisterBuiltin("EntityY", builtinEntityY)
	candy_evaluator.RegisterBuiltin("EntityZ", builtinEntityZ)
	candy_evaluator.RegisterBuiltin("PositionCamera", builtinPositionCamera)
	candy_evaluator.RegisterBuiltin("PointCamera", builtinPointCamera)
	candy_evaluator.RegisterBuiltin("cameraClsColor", builtinCameraClsColor)
	candy_evaluator.RegisterBuiltin("ColorEntity", builtinColorEntity)
	candy_evaluator.RegisterBuiltin("EntityColor", builtinColorEntity)
	candy_evaluator.RegisterBuiltin("EntityTexture", builtinEntityTexture)
	candy_evaluator.RegisterBuiltin("keyHit", builtinKeyHit)
	candy_evaluator.RegisterBuiltin("RenderWorld", builtinRenderWorld)

	candy_evaluator.RegisterBuiltin("guiWindowBox", builtinGuiWindowBox)
	candy_evaluator.RegisterBuiltin("guiGroupBox", builtinGuiGroupBox)
	candy_evaluator.RegisterBuiltin("guiLine", builtinGuiLine)
	candy_evaluator.RegisterBuiltin("guiPanel", builtinGuiPanel)
	candy_evaluator.RegisterBuiltin("guiStatusBar", builtinGuiStatusBar)
	candy_evaluator.RegisterBuiltin("guiDummyRec", builtinGuiDummyRec)
	candy_evaluator.RegisterBuiltin("guiScrollPanel", builtinGuiScrollPanel)
	candy_evaluator.RegisterBuiltin("guiNewScroll", builtinGuiNewScroll)
	candy_evaluator.RegisterBuiltin("guiGetScroll", builtinGuiGetScroll)
	// raygui — list / grid
	candy_evaluator.RegisterBuiltin("guiListView", builtinGuiListView)
	candy_evaluator.RegisterBuiltin("guiGrid", builtinGuiGrid)
	candy_evaluator.RegisterBuiltin("guiTabBar", builtinGuiTabBar)
	// raygui — dialogs
	candy_evaluator.RegisterBuiltin("guiMessageBox", builtinGuiMessageBox)
	candy_evaluator.RegisterBuiltin("guiTextInputBox", builtinGuiTextInputBox)
	// raygui — color pickers
	candy_evaluator.RegisterBuiltin("guiColorPicker", builtinGuiColorPicker)
	candy_evaluator.RegisterBuiltin("guiColorPanel", builtinGuiColorPanel)
	candy_evaluator.RegisterBuiltin("guiColorBarAlpha", builtinGuiColorBarAlpha)
	candy_evaluator.RegisterBuiltin("guiColorBarHue", builtinGuiColorBarHue)
	// raygui — drawing
	candy_evaluator.RegisterBuiltin("guiDrawIcon", builtinGuiDrawIcon)
	candy_evaluator.RegisterBuiltin("guiDrawRectangle", builtinGuiDrawRectangle)
	candy_evaluator.RegisterBuiltin("guiDrawText", builtinGuiDrawText)
	candy_evaluator.RegisterBuiltin("guiGetTextBounds", builtinGuiGetTextBounds)
	candy_evaluator.RegisterBuiltin("guiGetTextWidth", builtinGuiGetTextWidth)
	candy_evaluator.RegisterBuiltin("guiIconText", builtinGuiIconText)
	candy_evaluator.RegisterBuiltin("guiLoadIcons", builtinGuiLoadIcons)
	candy_evaluator.RegisterBuiltin("guiFade", builtinGuiFade)
	candy_evaluator.RegisterBuiltin("guiGetColor", builtinGuiGetColor)

	registerKidExtended()
}
