package candy_bindgen

import (
	"os"
	"strings"
)

// WriteCXXShimTemplate writes a starter C ABI bridge template for C++ libraries.
// Users can fill in each wrapper body to call into C++ classes/APIs.
func WriteCXXShimTemplate(path string, lib string, manifest *Manifest) error {
	var sb strings.Builder
	sb.WriteString("// generated by candywrap: C++ -> C ABI shim template\n")
	sb.WriteString("// Fill function bodies and include your C++ headers.\n\n")
	sb.WriteString("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
	if manifest != nil {
		for _, ex := range manifest.Externs {
			sb.WriteString(cProto(ex))
			sb.WriteString(" {\n")
			sb.WriteString("    // TODO: call into C++ implementation for symbol: ")
			if strings.TrimSpace(ex.Symbol) != "" {
				sb.WriteString(ex.Symbol)
			} else {
				sb.WriteString(ex.Name)
			}
			sb.WriteString("\n")
			if TypeToCandy(ex.ReturnType) != "void" {
				sb.WriteString("    return 0; // TODO\n")
			}
			sb.WriteString("}\n\n")
		}
	}
	sb.WriteString("#ifdef __cplusplus\n}\n#endif\n")
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

func cProto(ex ExternBinding) string {
	var sb strings.Builder
	sb.WriteString(strings.TrimSpace(ex.ReturnType))
	sb.WriteString(" ")
	if strings.TrimSpace(ex.Symbol) != "" {
		sb.WriteString(strings.TrimSpace(ex.Symbol))
	} else {
		sb.WriteString(strings.TrimSpace(ex.Name))
	}
	sb.WriteString("(")
	if len(ex.Params) == 0 {
		sb.WriteString("void")
	} else {
		for i, p := range ex.Params {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(strings.TrimSpace(p.Type))
			sb.WriteString(" ")
			sb.WriteString(strings.TrimSpace(p.Name))
		}
	}
	sb.WriteString(")")
	return sb.String()
}
