package candy_bindgen

import (
	"os"
	"strings"
)

func WriteLibraryDocs(path string, lib string, api *API, manifest *Manifest) error {
	var sb strings.Builder
	sb.WriteString("# " + lib + " bindings\n\n")
	sb.WriteString("Generated by `candywrap`.\n\n")
	if manifest != nil {
		sb.WriteString("## Import\n\n")
		sb.WriteString("```candy\n")
		sb.WriteString("import \"" + lib + ".candylib\"\n")
		sb.WriteString("```\n\n")
		if strings.TrimSpace(manifest.Namespace) != "" {
			sb.WriteString("Namespace prefix: `" + manifest.Namespace + "_`\n\n")
		}
	}
	sb.WriteString("## Functions\n\n")
	if api == nil || len(api.Functions) == 0 {
		sb.WriteString("_No functions extracted._\n")
	} else {
		for _, fn := range api.Functions {
			params := make([]string, 0, len(fn.Params))
			for _, p := range fn.Params {
				params = append(params, p.Name+": "+TypeToCandy(p.Type))
			}
			sb.WriteString("- `" + fn.Name + "(" + strings.Join(params, ", ") + ") -> " + TypeToCandy(fn.ReturnType) + "`\n")
		}
	}
	if api != nil && len(api.Constants) > 0 {
		sb.WriteString("\n## Constants\n\n")
		for _, c := range api.Constants {
			sb.WriteString("- `" + c.Name + "` = `" + c.Value + "`\n")
		}
	}
	if api != nil && len(api.Enums) > 0 {
		sb.WriteString("\n## Enums\n\n")
		for _, e := range api.Enums {
			sb.WriteString("- `" + e.Name + "`\n")
			for _, v := range e.Values {
				if strings.TrimSpace(v.Value) == "" {
					sb.WriteString("  - `" + v.Name + "`\n")
				} else {
					sb.WriteString("  - `" + v.Name + "` = `" + v.Value + "`\n")
				}
			}
		}
	}
	if api != nil && len(api.Types) > 0 {
		sb.WriteString("\n## Types\n\n")
		for _, t := range api.Types {
			sb.WriteString("- `" + t.Name + "` -> `" + t.CType + "`")
			if strings.TrimSpace(t.CandyType) != "" {
				sb.WriteString(" (Candy: `" + t.CandyType + "`)")
			}
			sb.WriteString("\n")
		}
	}
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}
