package candy_bindgen

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const envFixedGeneratedAt = "CANDY_BINDGEN_FIXED_TIME"

func BuildManifest(lib string, headers []string, externs []ExternBinding) Manifest {
	return Manifest{
		Library:     lib,
		Headers:     headers,
		GeneratedAt: manifestGeneratedAt(),
		Externs:     externs,
	}
}

func BuildManifestFromAPI(lib string, namespace string, headers []string, api *API) Manifest {
	externs := make([]ExternBinding, 0, len(api.Functions))
	for _, fn := range api.Functions {
		ex := ExternBinding{
			Name:       fn.Name,
			Symbol:     fn.Symbol,
			ReturnType: fn.ReturnType,
			Variadic:   fn.Variadic,
			Params:     make([]ExternParam, 0, len(fn.Params)),
		}
		for _, p := range fn.Params {
			ex.Params = append(ex.Params, ExternParam{Name: p.Name, Type: p.Type})
		}
		externs = append(externs, ex)
	}
	return Manifest{
		Library:     lib,
		Namespace:   strings.TrimSpace(namespace),
		Headers:     headers,
		GeneratedAt: manifestGeneratedAt(),
		Externs:     externs,
		Types:       api.Types,
		Enums:       api.Enums,
		Constants:   api.Constants,
	}
}

func manifestGeneratedAt() string {
	if fixed := strings.TrimSpace(os.Getenv(envFixedGeneratedAt)); fixed != "" {
		return fixed
	}
	return time.Now().UTC().Format(time.RFC3339)
}

func WriteManifest(path string, m Manifest) error {
	b, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

func WriteGlue(path string, lib string, externs []ExternBinding) error {
	var sb strings.Builder
	sb.WriteString("// generated by candywrap\n")
	sb.WriteString("#include <stddef.h>\n\n")
	for _, ex := range externs {
		sb.WriteString("// " + ex.Name + "\n")
	}
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

func WriteCandyStub(path string, lib string, externs []ExternBinding) error {
	var sb strings.Builder
	sb.WriteString("// generated helper stubs (optional)\n")
	sb.WriteString("import \"" + lib + ".candylib\"\n\n")
	for _, ex := range externs {
		params := make([]string, 0, len(ex.Params))
		for _, p := range ex.Params {
			params = append(params, p.Name+": "+TypeToCandy(p.Type))
		}
		ret := TypeToCandy(ex.ReturnType)
		sb.WriteString("extern fun " + ex.Name + "(" + strings.Join(params, ", ") + "): " + ret + " { }\n")
	}
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

// WriteCandyNamespaceStub emits thin wrapper functions with shorter names that call namespaced externs.
// Example: namespace `box2d`, extern `box2d_CreateBody` -> wrapper `fun CreateBody(...)`.
func WriteCandyNamespaceStub(path string, lib string, namespace string, externs []ExternBinding) error {
	ns := strings.TrimSpace(namespace)
	if ns == "" {
		return nil
	}
	var sb strings.Builder
	sb.WriteString("// generated namespace convenience wrappers\n")
	sb.WriteString("import \"" + lib + ".candylib\"\n\n")
	prefix := ns + "_"
	seen := map[string]struct{}{}
	externNames := map[string]struct{}{}
	for _, ex := range externs {
		externNames[strings.ToLower(strings.TrimSpace(ex.Name))] = struct{}{}
	}
	for _, ex := range externs {
		candyName := strings.TrimSpace(ex.Name)
		if !strings.HasPrefix(candyName, prefix) {
			continue
		}
		short := strings.TrimPrefix(candyName, prefix)
		short = strings.TrimSpace(short)
		if short == "" {
			continue
		}
		if isReservedCandyName(short) {
			short = ns + "_" + short
		}
		if _, clash := externNames[strings.ToLower(short)]; clash {
			short = ns + "_wrap_" + short
		}
		if _, ok := seen[strings.ToLower(short)]; ok {
			continue
		}
		seen[strings.ToLower(short)] = struct{}{}
		paramsDecl := make([]string, 0, len(ex.Params))
		argsCall := make([]string, 0, len(ex.Params))
		for _, p := range ex.Params {
			paramsDecl = append(paramsDecl, p.Name+": "+TypeToCandy(p.Type))
			argsCall = append(argsCall, p.Name)
		}
		ret := TypeToCandy(ex.ReturnType)
		if ret == "void" {
			sb.WriteString("fun " + short + "(" + strings.Join(paramsDecl, ", ") + ") {\n")
			sb.WriteString("  " + candyName + "(" + strings.Join(argsCall, ", ") + ")\n")
			sb.WriteString("}\n\n")
			continue
		}
		sb.WriteString("fun " + short + "(" + strings.Join(paramsDecl, ", ") + "): " + ret + " {\n")
		sb.WriteString("  return " + candyName + "(" + strings.Join(argsCall, ", ") + ")\n")
		sb.WriteString("}\n\n")
	}
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

func isReservedCandyName(name string) bool {
	switch strings.ToLower(strings.TrimSpace(name)) {
	case "if", "else", "for", "while", "return", "fun", "function", "extern", "import",
		"var", "val", "const", "type", "struct", "enum", "switch", "case", "default",
		"break", "continue", "try", "catch", "finally", "with", "delete", "end", "loop", "repeat":
		return true
	default:
		return false
	}
}

func DefaultLibName(headerPath string) string {
	base := filepath.Base(headerPath)
	ext := filepath.Ext(base)
	return strings.TrimSuffix(base, ext)
}
